### PR TITLE
Let benchmark.py generate .csv and .tex output files

### LINKED ISSUE #7: Generate .csv file when running benchmarks
We should automatically generate a `.csv` file when running benchmarks to format the results more easily into tables. In order to create a `.csv` structure that makes sense, think about how we would like the tables to be generated, see #11.

### PR DESCRIPTION
**Pull request by MrBeroxar**
Closes #7 and #11.

### CODE REVIEW

**Comment by MrBeroxar** [comment]
added .csv and .tex benchmarking

**Comment by PraxTube** [comment]
The output of the `.tex` file might has to be a little bit changed, but apart from that it looks good on first glance. Also, it seems like the script is generating a `.csv` file? Or is that something else?

**Comment by PraxTube** [comment]
Btw there are some tests that fail simply because of the format of the code. When you are in the `venv` with the dependencies installed from `requirements.txt` you can run `black .` and `flake8 .` to format and lint the code respectively.

**Comment by MrBeroxar** [comment]
ye .csv file also. I can do delet line 4 csv generta

**Comment by PraxTube** [comment]
It's actually quite nice that a `.csv` file is generated as well. That will make debugging much easier, it's also much easier to work with `.csv` files then `.tex` files. I would leave it in.

**Comment by MrBeroxar** [comment]
komm tel

**Comment by MrBeroxar** [comment]
oder cord

**Comment by PraxTube** [comment]
I cleaned up the commit history a bit and changed the way the .csv file is generated. It's not done yet, but I think you can see where it's going. We ultimately want to have a .csv file that generates [tables like this](https://github.com/PraxTube/chess-ai/blob/master/docs/milestones/one/benchmark-table.svg). So only one board from each stage (early, mid, late). Just take the first one from each. I would like you to finish this if possible, would be great if you could get it done ASAP, but I don't expect to be able to merge this today. Also note that we generate the tables differently then the way they are right now.

@MrBeroxar

**Comment by PraxTube** [comment]
If you encounter problems when pulling the changes locally, you can run `git reset --hard origin/csv-text-benchmarking-export`. Note that this will reset your local branch, so if you have any changes (even commits) they will be reset.

**Comment by PraxTube** [comment]
We would want an output like this as our `.tex` output

```latex
\begin{table}[ht!]
  \caption{Benchmark results of the Basic AI.}
	\label{tab:benchmark}
	\centering
	\begin{tabular}{cccc}
		\toprule
		Tested Category & Early-Game & Mid-Game & Late-Game \\ \toprule
    Fen Conversion & 13 $\upmu$s & 15 $\upmu$s & 10 $\upmu$s \\ %\midrule
		Legal Move Gen & 155 $\upmu$s & 968 $\upmu$s & 188 $\upmu$s \\
		Making Move & 5 $\upmu$s & 5 $\upmu$s & 5 $\upmu$s \\
		Evaluate Board & 205 $\upmu$s & 210 $\upmu$s & 194 $\upmu$s \\
		Best Move Search & 8.5 ms & 9.7 ms & 3.1 ms \\ \bottomrule
	\end{tabular}
\end{table}
```

**Comment by PraxTube** [comment]
Given that things have become very werid and complex, I think it would be best if you would create a fresh branch (preferably on the main repo, you should have the access rights to do so) and create the changes there. I also included your fix in the master branch for the logging.

@MrBeroxar

**Review by PraxTube — APPROVED** [review]

**Pull request merged**
